# Tensor Flow

### 1. What is TensorFlow?

- An open-source framework developed by Google.

- Used for: machine learning, deep learning, and numerical computation.

- Works with tensors, which are multi-dimensional arrays (like NumPy arrays).

### 2.TensorFlow Structure: Modules Overview

**Module**	**Purpose**
- **tensorflow.core**	Core engine (low-level APIs).
- **tensorflow.keras**	High-level APIs for building models easily.
- **tensorflow.data**	Efficient input pipelines (handling data).
- **tensorflow.estimator**	Distributed training and pre-built estimators.
- **tensorflow.lite**	For deploying models on mobile devices.
- **tensorflow.hub**	Reusable pre-trained models.


We’ll focus mostly on tensorflow.keras, tensorflow.data, and tensorflow.core (tensors and ops).

## What is a Tensor?

- A Tensor is just a fancy word for a multi-dimensional array — like:

- A scalar is a 0D tensor (5)

- A vector is a 1D tensor ([1, 2, 3])

- A matrix is a 2D tensor ([[1, 2], [3, 4]])

- Higher dimensions are also possible (3D, 4D, etc.)

### Creating Tensors in TensorFlow

In [21]:
import tensorflow as tf

In [22]:
#scalar - 0D tensor

In [23]:
scalar =tf.constant(5)
print(scalar,"scalar")

tf.Tensor(5, shape=(), dtype=int32) scalar


In [24]:
#vector - 1D tensor 

In [25]:
vector =tf.constant([1.0,2.0,3.0])
print(vector,"vector")

tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32) vector


In [26]:
#matrix - 2 d tensor

In [27]:
matrix = tf.constant([[1,2],[3,4]])
print("Matrix:\n",matrix)

Matrix:
 tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [28]:
#3d tesnor

In [29]:
tensor3d = tf.constant([[[1], [2]], [[3], [4]]])
print("3D Tensor:\n",tensor3d)

3D Tensor:
 tf.Tensor(
[[[1]
  [2]]

 [[3]
  [4]]], shape=(2, 2, 1), dtype=int32)


## Tensor Properties

In [30]:
print("Shape:", matrix.shape)

Shape: (2, 2)


In [31]:
print("Rank (dimensions):", tf.rank(matrix))

Rank (dimensions): tf.Tensor(2, shape=(), dtype=int32)


In [32]:
print("Datatype:", matrix.dtype)

Datatype: <dtype: 'int32'>


## Tensor Operations

In [33]:
a = tf.constant([10, 20])
b = tf.constant([1, 2])

In [34]:
# Element-wise operations
print("Addition:", tf.add(a, b))       


Addition: tf.Tensor([11 22], shape=(2,), dtype=int32)


In [35]:
print("Multiplication:", tf.multiply(a, b))  

Multiplication: tf.Tensor([10 40], shape=(2,), dtype=int32)


### 4. Variables vs Constants

**tf.constant:** values cannot change

**tf.Variable:** values can change (used in training)

In [37]:
v = tf.Variable([1.0, 2.0])
print("Before update:", v.numpy())


Before update: [1. 2.]


In [38]:
# Update variable
v.assign([3.0, 4.0])
print("After update:", v.numpy())

After update: [3. 4.]


### 5. Reshape and Cast

In [39]:
# Reshape a tensor
t = tf.constant([[1, 2], [3, 4]])
reshaped = tf.reshape(t, [4])
print("Reshaped:", reshaped)

Reshaped: tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [40]:
# Change data type
f = tf.constant([1.5, 2.5])
i = tf.cast(f, dtype=tf.int32)
print("Casted:", i)

Casted: tf.Tensor([1 2], shape=(2,), dtype=int32)


### Concepts You’ll Learn Along the Way

**Concept	Example**
- **Tensors**	tf.constant, tf.Variable
- **Models**	Sequential vs Functional API
- **Layers**	Dense, Conv2D, LSTM
- **Loss Functions**	MSE, CrossEntropy
- **Optimizers**	SGD, Adam
- **Callbacks**	EarlyStopping, ModelCheckpoint
- **Pipelines**	tf.data.Dataset
- **Saving models**	model.save() and tf.keras.models.load_model()

### Next Steps

After this intro, we can move to:

- Classification problems (e.g., MNIST digits)

- Working with tf.data pipelines

- **Using pre-trained models from TensorFlow Hub**

- Creating deep learning models (CNNs, RNNs)

# Simple ML Model in TensorFlow - Linear Regression

In [41]:
pip install matplotlib

  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
  Using cached pyparsing-3.2.3-py3-none-any.whl.metadata (5.0 kB)
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ----------- ---------------------------- 2.4/8.1 MB 11.2 MB/s eta 0:00:01
   ----------------------- ---------------- 4.7/8.1 MB 11.9 MB/s eta 0:00:01
   ----------------------------------- ---- 7.1/8.1 MB 11.8 MB/s eta 0:00:01
   ---------------------------------------- 8.1/8.1 MB 10.8 MB/s eta 0:00:00
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
   ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
   ---------------------------------------- 2.2/2.2 MB 10.4 MB/s eta 0:00:00
   ---------------------------------------- 0.0/2.6 MB ? eta -:--:--
   ----------------------------------- ---- 2.4/2.6 MB 12.2 MB/s eta 0:00:01
   ---------------------------------------- 2.6/2.6 MB 10.8 MB/s eta 0:00:00
Using cached pyparsing-3.2.3-py3-none-any.whl (111 kB)
Note: you may ne

In [42]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt


In [43]:
#Create Dummy Data
X = np.array([1, 2, 3, 4, 5], dtype=float)
y = np.array([3, 5, 7, 9, 11], dtype=float)  # y = 2x + 1

In [45]:
#Build the Model

model = tf.keras.Sequential([
    tf.keras.layers.Dense(units=1, input_shape=[1])
])


C:\Users\DELL 4\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [46]:
#Compile the Model
model.compile(optimizer='sgd', loss='mean_squared_error')



In [47]:
#Train the Model

model.fit(X, y, epochs=100)


Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 411ms/step - loss: 136.6714
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 79.6460
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 46.4143
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 27.0486
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 15.7632
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 9.1867
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 5.3541
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 3.1208
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 182ms/step - loss: 1.8192
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 1.0608
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 0.6188
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 0.3612
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 0.2111
Epoch 14/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - loss: 0.1236
Epoch 15/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - loss: 0.0726
Epoch 16/10

In [49]:
#Predict
#print(model.predict([6]))  # Should be close to 13


In [50]:
import numpy as np

# Proper input shape (2D array with 1 feature)
print(model.predict(np.array([[6.0]])))  # Output will be close to 13.0


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
[[13.043752]]
